version: '3.4'

services:
  clock:
    build:
      context: .
      target: clock
      cache_to: 
       - user/app:cache
       - type=local,dest=path/to/cache
  display:
    build:
      context: .
      target: display
  timer:
    build:
      context: .
      target: timer
